# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_article_options_article_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.CharField(max_length=255, verbose_name='Header'),
        ),
    ]
