# Generated by Django 6.0.7 on 2026-08-10 18:26

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_article_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=articles.models.advert_cover_directory_path, verbose_name='Cover image'),
        ),
    ]
