# Generated by Django 6.0.7 on 2026-08-17 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_owners(apps, schema_editor):
    BuildingUnit = apps.get_model('articles', 'BuildingUnit')
    BuildingUnitUser = apps.get_model('articles', 'BuildingUnitUser')
    for unit in BuildingUnit.objects.all():
        for user in unit.owners.all():
            BuildingUnitUser.objects.create(building_unit=unit, user=user, role='owner')


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_advert_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingUnitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant')], default='owner', max_length=10, verbose_name='Role')),
                ('building_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_users', to='articles.buildingunit', verbose_name='Building unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['building_unit', 'role', 'user'],
                'unique_together': {('building_unit', 'user', 'role')},
            },
        ),
        migrations.RunPython(migrate_existing_owners, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='buildingunit',
            name='owners',
        ),
        migrations.AddField(
            model_name='buildingunit',
            name='users',
            field=models.ManyToManyField(related_name='building_units', through='articles.BuildingUnitUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
