# Generated by Django 6.0.7 on 2026-08-20 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_preferences_named_template_placeholders'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('enum', 'Choice list'), ('datetime', 'Date/time'), ('boolean', 'Yes/No')], default='text', max_length=10, verbose_name='Type')),
                ('enum_options', models.CharField(blank=True, help_text="Only used when Type is 'Choice list', e.g.: malý,střední,velký", max_length=500, verbose_name='Options (comma-separated)')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Entity type')),
            ],
            options={
                'ordering': ['content_type', 'name'],
                'permissions': (('svjis_edit_admin_custom_fields', 'Can edit Custom fields'),),
                'unique_together': {('content_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='articles.customfielddefinition')),
            ],
            options={
                'unique_together': {('field_definition', 'content_type', 'object_id')},
            },
        ),
    ]
