# Generated by Django 6.0.7 on 2026-08-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_projectstatus_tag_project_projectasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
