# Generated by Django 6.0.7 on 2026-08-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_project_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatus',
            name='color',
            field=models.CharField(choices=[('slate', 'Grey'), ('brand', 'Teal'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('green', 'Green'), ('cyan', 'Cyan')], default='slate', max_length=10, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('slate', 'Grey'), ('brand', 'Teal'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('green', 'Green'), ('cyan', 'Cyan')], default='slate', max_length=10, verbose_name='Color'),
        ),
    ]
