# Generated by Django 6.0.7 on 2026-08-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_alter_projectstatus_color_alter_tag_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Checked')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='articles.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
