# Generated by Django 6.0.7 on 2026-08-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_alter_projectstatus_color_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingunituser',
            name='share_denominator',
            field=models.IntegerField(blank=True, null=True, verbose_name='Share denominator'),
        ),
        migrations.AddField(
            model_name='buildingunituser',
            name='share_numerator',
            field=models.IntegerField(blank=True, null=True, verbose_name='Share numerator'),
        ),
    ]
